### ISSUE TITLE
Unclear if :relationships can be hydrated

### ISSUE THREAD

**Issue by vemv** [Netflix/fast_jsonapi#105] opened 2018-03-02 17:37 UTC
Hi!

Dunno if this is more of a concern of http://jsonapi.org/, but:

it is unclear whether the items contained in `:relationships` can/should have richer keys than just `id` and `type`.

`"relationships":{"foos":{"data":[{"id":"2","type":"foo"}]},"bars":{"data":[{"id":"8","type":"bar"}]}}`

When one sees this generated json, may wonder "can I have more fields there?"

I am aware that there's `included`,  but ideally one would avoid generating bloated representations. Particularly for a performance-sensitive lib :)

Cheers - Victor

**Comment by devtoro** [comment] 2018-03-03 19:27
This is the json-api "standard". Maybe you could try GraphQL for what you ask or you could send your data under the "included" key like so:

```
"data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    }
  }
],
"included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }]
```

**Comment by hidde-jan** [comment] 2018-03-05 06:43
This is (kind of) a duplicate of https://github.com/Netflix/fast_jsonapi/issues/101, but with the inclusion of the request for sparse fieldsets. JSON API already has specified how apis should handle these things, with includes (http://jsonapi.org/format/#fetching-includes) and sparse fieldsets (http://jsonapi.org/format/#fetching-sparse-fieldsets).

Some more pointers to the JSON API docs in the readme might squash these questions. It seems that sparse field sets are currently not supported.

**Comment by shishirmk** [comment] 2018-03-18 22:19
The request is not supported by jsonapi standard as @hidde-jan has answered. A combination of includes and sparse fieldsets should provide similar functionality. Includes is supported by not sparse fieldsets.

Closing as sparse field sets are already captured as an enhancement

**Closed by shishirmk** 2018-03-18 22:19 UTC
