### ISSUE TITLE
Cannot specify condition for attribute

### ISSUE THREAD

**Issue by kquet** [Netflix/fast_jsonapi#187] opened 2018-04-24 22:59 UTC
There does not seem to be a way to conditionally add attributes to the serialized object. There are cases where I do not want `nil` for the value, I simply no attribute. Is there no way to do the following:

```
class MovieSerializer
  include FastJsonapi::ObjectSerializer

  attributes :name, :year
  # with if/unless conditions, defined method below
  attribute :country, if: :condition?
  
  # without if, method is default include_<attr>?
  attribute :genre

  def condition?
    object.country.present?
  end

  def include_genre?
    !object.genre.eql?('death metal')
  end
end
```

**Comment by shishirmk** [comment] 2018-05-21 00:30
duplicate of #185

**Closed by shishirmk** 2018-05-21 00:30 UTC
