### ISSUE TITLE
Regression: Date/Time is no longer serialized as ISO8601

### ISSUE THREAD

**Issue by martndemus** [Netflix/fast_jsonapi#135] opened 2018-03-22 09:56 UTC
I upgraded from 1.0.17 to 1.1.1 and somewhere (likely #58) the way date/timestamps are serialized regressed from being ISO8601 strings to simple time strings. Luckily my serializer specs caught it.

```diff
-      "created_at": "2018-03-22T09:45:00.246Z",
-      "updated_at": "2018-03-22T09:45:00.246Z",
+      "created_at": "2018-03-22 09:45:00 UTC"
+      "updated_at": "2018-03-22 09:45:00 UTC",
```

**Comment by bf4** [comment] 2018-03-22 16:01
The change

```diff
-        MultiJson.dump(payload) if payload.present?
+        FastJsonapi::MultiToJson.to_json(payload) if payload.present?
```

should used the same oj configs as multijson, as well as for the other json gems.  I'm guessing you don't have Oj installed and got bit by the bug fixed by https://github.com/Netflix/fast_jsonapi/pull/130

**Comment by bf4** [comment] 2018-03-27 06:06
@shishirmk IIRC, the bug fixed by #130 only affected installs lacking Oj. Perhaps I'm wrong about that. In any case it should be pretty easy to debug what's going on by 

```ruby
FastJsonapi::MultiToJson.to_json_method # => what's the output of this?

# and to remove any doubt
$VERBOSE = true
FastJsonapi::MultiToJson.logger(STDOUT)
FastJsonapi::MultiToJson.reset_to_json!
FastJsonapi::MultiToJson.to_json(payload)
```

Another possibility is that it's using  `%(::ActiveSupport::JSON.encode(object))` which wasn't part of the MultiJSON cascade.

It would be easier to reproduce and debug in discussion with @martndemus which is why I offered. There's some info that would be helpful just as other gems installed and a unix time that could be used for comparison.

**Comment by martndemus** [comment] 2018-03-28 11:58
Adding OJ as dep did fix it. So I guess that's what's happening. Would adding OJ by default make sense to keep backwards compat?

**Comment by bf4** [comment] 2018-03-28 16:10
@martndemus OJ depends on CRuby.  did you try debugging the code as I suggested? I think if you were to `bundle open fast_jsonapi` and comment out the active support line, you'd get your original behavior.

**Comment by neongrau** [comment] 2018-04-03 15:14
Having the same issue. But added to that when i installed OJ, serialization times doubled. 
Which was due to OJ not being set for rails_optimize. But then can't activate Rails optimizations as OJ (3.5) segfaults with that when encountering Time objects before 1970. So i have either wrongly formatted date strings in the JSON output, horribly slow serialization or a segfaulting ruby.

**Comment by bf4** [comment] 2018-04-03 21:58
Just putting it out there again, I'll pair with anyone who can reproduce this.  http://www.benjaminfleischer.com/pair/ or if you can make a test repo I'll look at it.

**Comment by shishirmk** [comment] 2018-05-21 00:44
Closing as there is no response and we have released a new version of the gem v1.2

**Closed by shishirmk** 2018-05-21 00:44 UTC
Labels: bug

**Comment by dominiceden** [comment] 2018-07-30 20:40
I had this issue too with version `1.1.1`. Solved by installing the `oj` gem.

**Comment by bf4** [comment] 2018-08-01 03:58
@dominiceden would you be interested in trying the debug I mentioned in https://github.com/Netflix/fast_jsonapi/issues/135#issuecomment-376407721 or pairing with me to see what the problem was?

**Comment by bf4** [comment] 2018-08-17 20:44
@nicolasrouanne great! Please contact me at http://www.benjaminfleischer.com/pair/

In the meantime, what's the output of

```ruby
FastJsonapi::MultiToJson.to_json_method # => what's the output of this?
```

```ruby
payload = .....
# and to remove any doubt
$VERBOSE = true
FastJsonapi::MultiToJson.logger(STDOUT)
FastJsonapi::MultiToJson.reset_to_json!
FastJsonapi::MultiToJson.to_json(payload)
```

**Comment by nicolasrouanne** [comment] 2018-08-21 11:08
_Before_ installing `oj`
```ruby
[1] pry(main)> FastJsonapi::MultiToJson.to_json_method
=> "def _fast_to_json(object)\n JSON.fast_generate(object, create_additions: false, quirks_mode: true)\nend"
...
[5] pry(main)> FastJsonapi::MultiToJson.to_json(@boat)
D, [2018-08-21T13:05:43.217843 #13519] DEBUG -- : Defining FastJsonapi::MultiToJson._fast_to_json as "def _fast_to_json(object)\n JSON.fast_generate(object, create_additions: false, quirks_mode: true)\nend"
=> "\"#<Boat:0x00007ff5aaa949b0>\""
```

_After_ installing `oj`
```ruby
[1] pry(main)> FastJsonapi::MultiToJson.to_json_method
=> "def _fast_to_json(object)\n ::Oj.dump(object, mode: :compat, time_format: :ruby, use_to_json: true)\nend"
...
[7] pry(main)> FastJsonapi::MultiToJson.to_json(@boat)
D, [2018-08-21T13:03:25.941746 #13304] DEBUG -- : Defining FastJsonapi::MultiToJson._fast_to_json as "def _fast_to_json(object)\n ::Oj.dump(object, mode: :compat, time_format: :ruby, use_to_json: true)\nend"
=> "{\"id\":1,\"name\":\"Dratini\",\"created_at\":\"2018-08-17T14:16:30.115Z\",\"updated_at\":\"2018-08-17T14:16:30.115Z\",\"booking_system_id\":1,\"company_id\":1,\"location_id\":1,\"boat_model_id\":1,\"year\":3672}"
```

**Comment by nicolasrouanne** [comment] 2018-08-21 15:00
`@boat` is an _ActiveRecord Model_ instance

```ruby
[1] pry(main)> @boat = Boat.first
  Boat Load (2.8ms)  SELECT  "boats".* FROM "boats" ORDER BY "boats"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Boat:0x00007f7f024ac418
 id: 1,
 name: "Dratini",
 created_at: Fri, 17 Aug 2018 14:16:30 UTC +00:00,
 updated_at: Fri, 17 Aug 2018 14:16:30 UTC +00:00,
 booking_system_id: 1,
 company_id: 1,
 location_id: 1,
 boat_model_id: 1,
 year: 3672>
```

I'm using `ruby` _2.5.1_ and `json` _2.1.0_

> I'd be interested in seeing which JSON command is the 'right' one.

What do you mean?

**Comment by bf4** [comment] 2018-08-21 18:52
My guess is you mean you have a poor with activemodel::model mixed in but
not activemodel::serialization
