### ISSUE TITLE
fast_jsonapi may not as fast as it is expected to be in a real Rails environment?

### ISSUE THREAD

**Issue by shuheiktgw** [Netflix/fast_jsonapi#118] opened 2018-03-13 02:10 UTC
Hi, thank you so much for creating such a great project and I'm really excited to be able to serialize json faster.

I just took a benchmark in a sample Rails application and it turned out that fast_jsonapi may not as fast as it is expected to be compared to AMS in this case... I created `Company has many employees` relationship with ActiveRecord and took benchmarks both for ActiveModel::Serializer and FastJsonapi.

Results are below.

|  | Serializer | 1 company | 25 companies |
|:-----------:|:------------:|:------------|:------------|
| 1 employee | AMS | 15.811999997822568 | 31.31099999882281 |
| 1 employee | FJA | 13.44200001040008 | 9.640000003855675 |
| 25 employees | AMS | 8.14800000807736 | 111.75599999842234 |
| 25 employees | FJA | 5.560000005061738 | 91.2769999995362 |
| 250 employees | AMS | 54.18900000222493 | 794.873999999254 |
| 250 employees | FJA | 31.94699999585282 | 791.3709999993443 |

Also all the source codes and results are placed [here](https://github.com/shuheiktgw/benchmark_fast_jsonapi). 

The results show that FJA is not much faster than AMS, and I'm wondering the reason why.

Does anybody have any thoughts or ideas on why FJA is not that faster than AMS in this case? Probably my way of taking a benchmark is not good?  Or maybe in my local environment, other process such as db accesses are dominant factors for serialization?

**Comment by shishirmk** [comment] 2018-03-13 05:40
@shuheiktgw Thank you for all the pull requests you have made. I just merged them all. I have to look into your example to understand how you get the numbers above. However I can confirm that we use this in production and it has reduced our serialization time to almost nothing. Which in turn made the endpoint around 40 percent faster.

In the mean time to understand more about how we measure and what are our intent is please read https://github.com/Netflix/fast_jsonapi/blob/master/performance_methodology.md

There have also been several issues and one pull request about this topic and I have answered all of them so please read them too. After i release the next version I should have sometime to look into this particular case and get back to you.

**Comment by christophersansone** [comment] 2018-03-18 18:05
@shuheiktgw Thanks for helping us verify the performance results.  I just did a quick glance at the example and noticed a couple possible discrepancies.

1. Is AMS configured to use the JSON:API serializer?  I did not see anything that set it as such (though I may have missed it).

2. I see that you are serializing the `has_many` relationship for FJA, but not AMS.  Is that correct?

As a result, it's possible that this benchmark is not accurate because it is not producing the same output.  Again, I may be wrong here, but this is what I noticed with a quick look.  Would you be willing to update your specs to include some assertions that the output of both your AMS and FJA serializations are identical?  If we can demonstrate that they are indeed identical, then we can look deeper into why the performance results are not as expected.

**Comment by shishirmk** [comment] 2018-03-18 22:21
Thanks for taking a look @christophersansone. @shuheiktgw let me know what you think about the above comments

**Comment by shishirmk** [comment] 2018-03-30 00:19
@shuheiktgw Were you able to see the performance difference after making changes based on @christophersansone 's comment?

**Comment by shuheiktgw** [comment] 2018-04-04 10:14
@christophersansone @shishirmk 
Thank you so much for your comments!
I will make some changes based on the your suggestions and see the results!

**Comment by shuheiktgw** [comment] 2018-04-06 11:07
Hi, I updated [my benchmark](https://github.com/shuheiktgw/benchmark_fast_jsonapi) in mainly following two ways.

1. Change to use json_api adaptor for AMS
2. Change to use `to_json ` for AMS not `as_json` since AMS returns hash if `as_json` is called.

Also, I took two patterns of benchmarks. One that AMS uses `json_api adaptor` and the one AMS uses `default adaptor`. The results are below.

### `FastJsonapi` (FJA) against`ActiveModel::Serializer` (AMS) with `json_api adapter`

|  | Serializer | 1 company | 25 companies |
|:-----------:|:------------:|:------------|:------------|
| 1 employee | AMS | 32.995999999911874 | 60.81799999992654 |
| 1 employee | FJA | 19.072999999934837 | 8.621999999832042 |
| 25 employees | AMS | 35.11500000013257 | 577.1009999998569 |
| 25 employees | FJA | 6.498000000192405 | 85.53800000026968 |
| 250 employees | AMS | 246.90600000030827 | 5089.174999999614 |
| 250 employees | FJA | 32.62899999981528 | 754.1630000000623 |

### `FastJsonapi` against`ActiveModel::Serializer` with `default adapter`

|  | Serializer | 1 company | 25 companies |
|:-----------:|:------------:|:------------|:------------|
| 1 employee | AMS | 15.873000000283355 | 24.73100000042905 |
| 1 employee | FJA | 16.28900000014255 | 8.800000000519503 |
| 25 employees | AMS | 7.133000000067113 | 134.71600000048056 |
| 25 employees | FJA | 6.07899999977235 | 84.16800000031799 |
| 250 employees | AMS | 52.87399999997433 | 855.4990000002363 |
| 250 employees | FJA | 31.502000000728003 | 1261.395999999877 |

The new results show that FJA is much faster than AMS with json_api adaptor. And FJA is relatively faster than AMS with default adaptor!

BTW, for @christophersansone 's second comment, `I see that you are serializing the has_many relationship for FJA, but not AMS. Is that correct?`, default adaptor fetches data with has_many relationship by default (you do not need to call `include` explicitly), so I would say this is a fair comparison...?

Anyway, I'm glad that I can show fast_jsonapi is much faster than ams in some way, and I'm happy to hear feedbacks on this results! Thank you! 👍

**Comment by shuheiktgw** [comment] 2018-04-07 01:01
@christophersansone 

Thank you so much for your comments! Of course!
Here are the outputs of one company, one employee of each serializers.

### FJA
```
{
  "data": [
    {
      "id": "547",
      "type": "fja_company",
      "attributes": {
        "name": "Gooogle",
        "updated_at": "2018-04-07 00:55:39 UTC",
        "created_at": "2018-04-07 00:55:39 UTC"
      },
      "relationships": {
        "fja_employees": {
          "data": [
            {
              "id": "50233",
              "type": "fja_employee"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "id": "50233",
      "type": "fja_employee",
      "attributes": {
        "name": "Employee 2",
        "position": "engineer",
        "age": 25,
        "updated_at": "2018-04-07 00:55:39 UTC",
        "created_at": "2018-04-07 00:55:39 UTC"
      },
      "relationships": {
        "fja_company": {
          "data": {
            "id": "547",
            "type": "fja_company"
          }
        }
      }
    }
  ]
}
```

### AMS with json_api adaptor

```
{
  "data": [
    {
      "id": "547",
      "type": "ams-companies",
      "attributes": {
        "name": "Gooogle",
        "updated-at": "2018-04-07 00:55:39 UTC",
        "created-at": "2018-04-07 00:55:39 UTC"
      },
      "relationships": {
        "ams-employees": {
          "data": [
            {
              "id": "50233",
              "type": "ams-employees"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "id": "50233",
      "type": "ams-employees",
      "attributes": {
        "name": "Employee 1",
        "position": "engineer",
        "age": 25,
        "updated-at": "2018-04-07 00:55:39 UTC",
        "created-at": "2018-04-07 00:55:39 UTC"
      },
      "relationships": {
        "ams-company": {
          "data": {
            "id": "547",
            "type": "ams-companies"
          }
        }
      }
    }
  ]
}
```

### AMS with default adaptor

```
[
  {
    "name": "Gooogle",
    "updated_at": "2018-04-07 01:00:37 UTC",
    "created_at": "2018-04-07 01:00:37 UTC",
    "ams_employees": [
      {
        "name": "Employee 1",
        "position": "engineer",
        "age": 25,
        "updated_at": "2018-04-07 01:00:37 UTC",
        "created_at": "2018-04-07 01:00:37 UTC"
      }
    ]
  }
]
```

**Comment by shishirmk** [comment] 2018-04-09 06:18
Looks like the issue is resolved so closing this

**Closed by shishirmk** 2018-04-09 06:18 UTC
