### ISSUE TITLE
Cant include polymorphic associations

### ISSUE THREAD

**Issue by krzkrzkrz** [Netflix/fast_jsonapi#266] opened 2018-07-05 08:44 UTC
Not sure if this is related to https://github.com/Netflix/fast_jsonapi/pull/236

Following the example at the Readme. If `User` serializer has `belongs_to :profile, polymorphic: true`.

Lets say, I have an `Article` serializer that has: `belongs_to :user`

```
ArticleSerializer.new(article, { include: [:'user.profile'] })
```
I end up with an error `NotImplementedError: NotImplementedError`

Could also be related to https://github.com/Netflix/fast_jsonapi/issues/231

**Comment by lassiter** [comment] 2018-07-05 20:20
Are your users or profiles polymorphic?

If so, It is apart of #231, the object serializer has an exception for polymorphic includes.

**Comment by krzkrzkrz** [comment] 2018-07-05 21:12
@lassiter `profile` is polymorphic

**Comment by lassiter** [comment] 2018-07-15 23:36
Shishir, does this look like it'll need to be a major refactor support
polymorphics?

*Lassiter Gregg*
*lassitergregg@gmail.com <lassitergregg@gmail.com>*
*cell (832) 495-9903*

On Sun, Jul 15, 2018 at 2:28 PM, Shishir Kakaraddi <notifications@github.com

**Comment by shishirmk** [comment] 2018-07-17 05:10
duplicate of #231

**Closed by shishirmk** 2018-07-17 05:10 UTC
Labels: enhancement

**Comment by jshow** [comment] 2018-07-18 21:09
How does this look ? https://github.com/Netflix/fast_jsonapi/pull/275

**Comment by krzkrzkrz** [comment] 2018-07-20 05:13
The PR from @jshow is exactly what I need. Any chance we can merge this asap?

**Comment by lassiter** [comment] 2018-07-20 20:22
I think that PR #275 still needs tests first. There's nothing validating it works.
