### ISSUE TITLE
Conditional attributes in Serializer

### ISSUE THREAD

**Issue by Branksy** [Netflix/fast_jsonapi#191] opened 2018-04-26 19:35 UTC
Say I have one UserSerializer.
How can I display a different set of attributes in the serializer depending on the context, e.g. show action v. index action, without creating two separate serializers?
Thanks.

**Comment by alienxp03** [comment] 2018-05-01 04:33
Looking forward to this feature too. Related PR I supposed? https://github.com/Netflix/fast_jsonapi/pull/153

**Comment by shishirmk** [comment] 2018-05-01 16:59
#153 has been merged to dev

**Comment by alienxp03** [comment] 2018-05-02 03:10
Awesome. Thanks @shishirmk

**Comment by TrevorHinesley** [comment] 2018-05-02 18:00
#153 does not include this functionality unfortunately. Right?

**Comment by shishirmk** [comment] 2018-05-21 00:30
Duplicate of #185

**Closed by shishirmk** 2018-05-21 00:30 UTC
